version: '3'

services:
  gameserver:
    build:
      context: .
      dockerfile: docker/Dockerfile.gameserver
    image: game-server
    tty: true
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - nats

  nats:
    image: nats-server
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'

  redis:
    image: redis
    ports:
      - '6379:6379'

networks:
  default:
    external:
      name: game
