version: '3'

services:
  nats:
    image: ${NATS_SERVER_IMAGE}
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222
    command:
      - "/bin/sh"
      - "-c"
      - "nats-server --config /etc/nats/nats-server.conf ${NATS_OPTS}"

  redis:
    image: ${REDIS_IMAGE}
    ports:
      - 6379:6379

  postgres:
    image: ${POSTGRES_IMAGE}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: 'game'

  api-server:
    image: ${API_SERVER_IMAGE}
    ports:
      - 9501:9501
    depends_on:
      - postgres
      - nats
      - redis
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 5 && yarn run-docker"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NATS_URL: nats://nats:4222
      BOTRUNNER_URL: http://botrunner:8081

  game-server:
    image: ${GAME_SERVER_IMAGE}
    tty: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - nats
      - api-server
    environment:
      PERSIST_METHOD: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      API_SERVER_URL: http://api-server:9501
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 10 && /app/game-server --server"

  botrunner:
    image: ${BOTRUNNER_IMAGE}
    tty: true
    ports:
      - 8081:8081
    depends_on:
      - api-server
      - game-server
    environment:
      API_SERVER_URL: http://api-server:9501
      PERSIST_METHOD: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

networks:
  default:
    external:
      name: ${TEST_DOCKER_NET}
