# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.13

    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run game scripts test
          command: make script-test
