FROM golang:1.13.10-alpine3.11 AS builder

RUN mkdir /build 
ADD . /build/
WORKDIR /build 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o game-server .

FROM alpine:latest
COPY --from=builder /build/game-server /app/
COPY --from=builder /build/test/game-scripts /app/game-scripts

WORKDIR /app
# CMD ["/app/game-server", "--script-tests", "/app/game-scripts"]
CMD ["/app/game-server", "--server", "--nats-server", "nats"]
