FROM golang:1.13.10-alpine3.11 AS builder

WORKDIR $GOPATH/src/github.com/nats-io/nats-server

MAINTAINER Waldemar Quevedo <wally@synadia.com>

RUN apk add --update git

COPY ./nats-server ./
RUN CGO_ENABLED=0 GO111MODULE=off go build -v -a -tags netgo -installsuffix netgo -ldflags "-s -w -X github.com/nats-io/nats-server/server.gitCommit=`git rev-parse --short HEAD`" -o /app/nats-server
