version: '3'

services:
  nats:
    ports:
      - 4222:4222
      - 8222:8222
      - 9222:9222

  redis:
    ports:
      - 6379:6379

  postgres:
    ports:
      - 5432:5432

  api-server:
    ports:
      - 9501:9501
      - 9502:9502

  game-server-1:
    ports:
      - 8090:8080

  game-server-2:
    ports:
      - 8091:8080

  botrunner:
    ports:
      - 8081:8081
    volumes:
      - ./botrunner_scripts:/app/botrunner_scripts
      - ./system_test.sh:/app/system_test.sh

  timer:
    ports:
      - 8082:8082

  scheduler:
    ports:
      - 8083:8083

networks:
  default:
    external:
      name: ${TEST_DOCKER_NET}
